struct moviedetails person[300];
int count = 0;
int TicketGenerateId = 1000;
int changeticketprice(int);
void bookinghistory(int *,int,int );
int moviechoice(void);
void cancelticket(int *);        
void ticket1(int choice,char name[10],int id2,int price);
void ticket2(int choice,char name[10],int id2,int price);
void ticket3(int choice,char name[10],int id2,int price);
int cancelmovielist(void);
int getmovielist(void);
